name: CMake with vcpkg binary caching to GitHub Packages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - run: git config --global credential.helper '!f() { echo username=unused; echo password=${{ secrets.BUILD_PAT }}; }; f'
      shell: 'bash'
      name: 'git credential helper setup'
    
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.BUILD_PAT }}
        nuget-version: 'latest'
    
    - name: 'Setup binary caching'
      shell: 'bash'
      run: |
        nuget \
          sources add \
          -source "https://nuget.pkg.github.com/Vitaware-Ltd/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "Vitaware-Ltd" \
          -password "${{ secrets.BUILD_PAT }}"
        nuget \
          setapikey "${{ secrets.BUILD_PAT }}" \
          -source "https://nuget.pkg.github.com/Vitaware-Ltd/index.json"

    # Don't symlink vcpkg to the C drive when building dependencies as the harfbuzz build
    # uses a Python script that utilises os.path.relpath which fails due to the different drives.
    # Instead use --x-buildtrees-root
    #
    #- name: Create vcpkg directory
    #  run: |
    #    mkdir C:\vita_vcpkg
    #    New-Item -Path vcpkg -ItemType SymbolicLink -Value C:\vita_vcpkg

    - uses: friendlyanon/setup-vcpkg@v1
      with:
        committish: '91dd61bd441a68b4017b61011d0350b2e6aeeccf'
        cache: 'false'
  
    - run: Get-PSDrive
    - run: mkdir C:\vcpkg_buildtrees
    - run: mkdir C:\vcpkg_packages
    - run: mkdir C:\vcpkg_downloads
    
    - uses: ilammy/msvc-dev-cmd@v1
    
    - name: Configure CMake
      run: cmake -D "CMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DCMAKE_SYSTEM_VERSION="10.0.22621" -DVCPKG_INSTALL_OPTIONS="--x-buildtrees-root=C:/vcpkg_buildtrees;--x-packages-root=C:/vcpkg_packages;--x-downloads-root=C:/vcpkg_downloads" -B "${{github.workspace}}/build" -S "${{github.workspace}}/Source"
